# Generated by Django 6.0.1 on 2026-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='cargo_firma_1',
            field=models.CharField(default='RECTOR UNEMI', max_length=100, verbose_name='Cargo Autoridad 1'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='cargo_firma_2',
            field=models.CharField(default='VICERRECTORA ACADÉMICA', max_length=100, verbose_name='Cargo Autoridad 2'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='cuerpo_certificado',
            field=models.TextField(default='Por haber completado satisfactoriamente el curso de capacitación continua, demostrando compromiso y excelencia académica.', help_text='Texto principal del certificado'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='imagen_firma_1',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Autoridad 1'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='imagen_firma_2',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Autoridad 2'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='nombre_firma_1',
            field=models.CharField(default='Ph.D. Fabricio Guevara Viejó', max_length=100, verbose_name='Nombre Autoridad 1'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='nombre_firma_2',
            field=models.CharField(default='Ph.D. Jesennia Cárdenas Cobo', max_length=100, verbose_name='Nombre Autoridad 2'),
        ),
    ]
