# Generated by Django 6.0.1 on 2026-01-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lotecertificados_cargo_firma_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='cargo_firma_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo Autoridad 3'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='cargo_firma_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo Autoridad 4'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='imagen_firma_3',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Autoridad 3'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='imagen_firma_4',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Autoridad 4'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='nombre_firma_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Autoridad 3'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='nombre_firma_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Autoridad 4'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='cargo_firma_2',
            field=models.CharField(blank=True, default='VICERRECTORA ACADÉMICA', max_length=100, verbose_name='Cargo Autoridad 2'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='nombre_firma_2',
            field=models.CharField(blank=True, default='Ph.D. Jesennia Cárdenas Cobo', max_length=100, verbose_name='Nombre Autoridad 2'),
        ),
    ]
