# Generated by Django 6.0.1 on 2026-01-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lotecertificados_cargo_firma_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='logo_header_1',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Cabecera 1'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='logo_header_2',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Cabecera 2'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='logo_header_3',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo Cabecera 3'),
        ),
    ]
