# Generated by Django 4.2.8 on 2026-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_certificado_id_alter_lotecertificados_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='facultad',
            field=models.CharField(choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra')], db_index=True, default='FACI', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
