# Generated by Django 4.2.8 on 2026-01-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='color_primario',
            field=models.CharField(default='#162054', help_text='Color Principal (Hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='color_secundario',
            field=models.CharField(default='#D4AF37', help_text='Color Secundario (Hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='plantilla',
            field=models.CharField(choices=[('clasico', 'Clásico (Elegante)'), ('moderno', 'Moderno (Barra Lateral)'), ('geometrico', 'Geométrico (Formas)')], default='clasico', max_length=20),
        ),
    ]
