# Generated by Django 4.2.8 on 2026-01-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lotecertificados_color_primario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='color_terciario',
            field=models.CharField(default='#F3F4F6', help_text='Color Terciario/Detalle (Hex)', max_length=7),
        ),
    ]
