# Generated by Django 4.2.8 on 2026-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lotecertificados_color_terciario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecertificados',
            name='color_texto',
            field=models.CharField(default='#333333', help_text='Color del Texto (Hex)', max_length=7),
        ),
    ]
