# Generated by Django 4.2.8 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lotecertificados_color_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecertificados',
            name='imagen_firma_1',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Autoridad 1 (Base64)'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='imagen_firma_2',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Autoridad 2 (Base64)'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='imagen_firma_3',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Autoridad 3 (Base64)'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='imagen_firma_4',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Autoridad 4 (Base64)'),
        ),
    ]
