# Generated by Django 4.2.8 on 2026-02-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_lotecertificados_imagen_firma_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
