# Generated by Django 4.2.8 on 2026-02-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_certificado_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecertificados',
            name='cuerpo_certificado',
            field=models.TextField(default='Por haber asistido al seminario {curso}, desarrollando habilidades y conocimientos que enriquecen su perfil profesional y aportan valor a su hoja de vida.', help_text='Texto principal del certificado'),
        ),
    ]
