# Generated by Django 4.2.8 on 2026-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_lotecertificados_cuerpo_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecertificados',
            name='cuerpo_certificado',
            field=models.TextField(default='Por haber asistido al seminario {curso}, demostrando compromiso y excelencia en la adquisición de nuevos conocimientos.', help_text='Texto principal del certificado'),
        ),
    ]
