# Generated by Django 5.2.11 on 2026-03-01 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lotecertificados_cuerpo_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título descriptivo (ej: "Sesión Mañana - Lunes")', max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha de la Sesión')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=12, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('codigo_qr', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.lotecertificados', verbose_name='Seminario')),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia',
                'verbose_name_plural': 'Sesiones de Asistencia',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.certificado')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Si faltó sin justificación, se bloquea la cuenta.')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='core.certificado')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Confirmación de Asistencia',
                'verbose_name_plural': 'Confirmaciones de Asistencia',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
        migrations.AddIndex(
            model_name='sesionasistencia',
            index=models.Index(fields=['codigo_qr'], name='core_sesion_codigo__5a1db2_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionasistencia',
            index=models.Index(fields=['fecha', 'activa'], name='core_sesion_fecha_828703_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('sesion', 'certificado')},
        ),
        migrations.AlterUniqueTogether(
            name='confirmacionasistencia',
            unique_together={('certificado', 'sesion')},
        ),
    ]
