# Generated by Django 5.2.11 on 2026-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sesionasistencia_registroasistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionasistencia',
            name='capacidad',
            field=models.PositiveIntegerField(default=250, help_text='Máximo de participantes (por defecto 250)', verbose_name='Cupos Máximos'),
        ),
    ]
