# Generated by Django 5.2.11 on 2026-03-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sesionasistencia_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionasistencia',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.lotecertificados', verbose_name='Seminario'),
        ),
    ]
