# Generated by Django 5.2.11 on 2026-03-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sesionasistencia_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionasistencia',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12, verbose_name='Día'),
        ),
    ]
