# Generated by Django 5.2.11 on 2026-03-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sesionasistencia_dia_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('facultad', models.CharField(max_length=100, verbose_name='Facultad / Departamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Puesto')),
                ('razon_acceso', models.TextField(verbose_name='Razón por la que necesita acceso')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo del Rechazo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('usuario_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_acceso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creado')),
            ],
            options={
                'verbose_name': 'Solicitud de Acceso',
                'verbose_name_plural': 'Solicitudes de Acceso',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', '-fecha_solicitud'], name='core_solici_estado_8f8b6c_idx'), models.Index(fields=['email'], name='core_solici_email_7e94bd_idx')],
            },
        ),
    ]
