# Generated by Django 5.2.11 on 2026-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_cargo_motivo_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudacceso',
            name='razon_acceso',
        ),
        migrations.AddField(
            model_name='solicitudacceso',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo del Rechazo'),
        ),
    ]
