# Generated by Django 5.2.11 on 2026-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_razon_acceso_restore_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudacceso',
            name='facultad',
            field=models.CharField(choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra')], default='FACI', max_length=20, verbose_name='Facultad / Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(blank=True, choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra')], max_length=20),
        ),
    ]
