# Generated by Django 5.2.11 on 2026-03-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_solicitudacceso_facultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionasistencia',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='sesionasistencia',
            name='lugar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='confirmacionasistencia',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='core.certificado'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, upload_to='lotes_excel/'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.certificado'),
        ),
        migrations.AlterField(
            model_name='sesionasistencia',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='Cupos Máximos'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=200)),
                ('celular', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'indexes': [models.Index(fields=['email'], name='core_partic_email_323117_idx'), models.Index(fields=['cedula'], name='core_partic_cedula_31379b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cedula', ''), _negated=True), fields=('cedula',), name='unique_cedula_when_not_empty')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='confirmacionasistencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificado',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='core.participante'),
        ),
        migrations.AddField(
            model_name='confirmacionasistencia',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='core.participante'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.participante'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmacionasistencia',
            unique_together={('participante', 'sesion')},
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('sesion', 'participante')},
        ),
    ]
