# Generated by Django 5.2.11 on 2026-03-24 15:00

from django.db import migrations


def populate_participantes(apps, schema_editor):
    """Create Participante records from existing Certificado data and link FKs."""
    Certificado = apps.get_model('core', 'Certificado')
    Participante = apps.get_model('core', 'Participante')
    ConfirmacionAsistencia = apps.get_model('core', 'ConfirmacionAsistencia')
    RegistroAsistencia = apps.get_model('core', 'RegistroAsistencia')

    # Group certificates by person: first by cedula (non-GEN), then by email
    cedula_map = {}  # cedula -> Participante
    email_map = {}   # email -> Participante

    for cert in Certificado.objects.all().order_by('-created_at'):
        cedula = cert.cedula.strip()
        email = cert.email.strip().lower()
        is_generated_cedula = cedula.startswith('GEN-') or not cedula

        participante = None

        # Try to find by real cedula first
        if not is_generated_cedula and cedula in cedula_map:
            participante = cedula_map[cedula]
        # Then by email
        elif email and email in email_map:
            participante = email_map[email]

        if not participante:
            # Create new Participante
            participante = Participante.objects.create(
                cedula='' if is_generated_cedula else cedula,
                nombres=cert.nombres,
                apellidos=cert.apellidos,
                email=email,
                celular=cert.celular or '',
            )
            if not is_generated_cedula and cedula:
                cedula_map[cedula] = participante
            if email:
                email_map[email] = participante

        # Link certificate to participante
        cert.participante = participante
        cert.save(update_fields=['participante'])

    # Link ConfirmacionAsistencia to participante via certificado
    for conf in ConfirmacionAsistencia.objects.filter(participante__isnull=True).select_related('certificado'):
        if conf.certificado and conf.certificado.participante:
            conf.participante = conf.certificado.participante
            conf.save(update_fields=['participante'])

    # Link RegistroAsistencia to participante via certificado
    for reg in RegistroAsistencia.objects.filter(participante__isnull=True).select_related('certificado'):
        if reg.certificado and reg.certificado.participante:
            reg.participante = reg.certificado.participante
            reg.save(update_fields=['participante'])


def reverse_populate(apps, schema_editor):
    """Reverse: just clear the participante FKs."""
    Participante = apps.get_model('core', 'Participante')
    Participante.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sesionasistencia_descripcion_sesionasistencia_lugar_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_participantes, reverse_populate),
    ]
