# Generated by Django 5.2.11 on 2026-03-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_participantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hero', 'Encabezado Principal'), ('evento', 'Evento Destacado'), ('pasado', 'Evento Pasado / Noticia'), ('custom', 'Bloque Personalizado')], default='hero', max_length=20)),
                ('estilo', models.CharField(choices=[('hero_gradient', 'Hero - Gradiente con orbes animados'), ('hero_imagen', 'Hero - Imagen de fondo completa'), ('hero_split', 'Hero - Mitad imagen / mitad texto'), ('card_imagen_top', 'Card - Imagen arriba, texto abajo'), ('card_horizontal', 'Card - Imagen lateral, texto al lado'), ('card_solo_texto', 'Card - Solo texto con color de fondo')], default='hero_gradient', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('color_fondo', models.CharField(default='#162054', max_length=7)),
                ('color_texto', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_acento', models.CharField(default='#F58830', max_length=7)),
                ('boton_1_texto', models.CharField(blank=True, max_length=100)),
                ('boton_1_url', models.CharField(blank=True, max_length=500)),
                ('boton_1_icono', models.CharField(blank=True, default='fa-solid fa-arrow-right', max_length=50)),
                ('boton_2_texto', models.CharField(blank=True, max_length=100)),
                ('boton_2_url', models.CharField(blank=True, max_length=500)),
                ('boton_2_icono', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_bloques', to='core.sesionasistencia', verbose_name='Evento vinculado')),
            ],
            options={
                'verbose_name': 'Bloque de Landing',
                'verbose_name_plural': 'Bloques de Landing',
                'ordering': ['orden'],
            },
        ),
    ]
