# Generated by Django 5.2.11 on 2026-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_landingbloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingbloque',
            name='items_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='landingbloque',
            name='estilo',
            field=models.CharField(choices=[('hero_gradient', 'Hero - Gradiente con orbes animados'), ('hero_imagen', 'Hero - Imagen de fondo completa'), ('hero_split', 'Hero - Mitad imagen / mitad texto'), ('stats_bar', 'Stats - Barra de estadísticas'), ('steps_3', 'Steps - 3 pasos con iconos'), ('features_grid', 'Features - Grid de características'), ('cta_banner', 'CTA - Banner con botón'), ('card_imagen_top', 'Card - Imagen arriba, texto abajo'), ('card_horizontal', 'Card - Imagen lateral, texto al lado'), ('card_solo_texto', 'Card - Solo texto con color de fondo')], default='hero_gradient', max_length=30),
        ),
        migrations.AlterField(
            model_name='landingbloque',
            name='tipo',
            field=models.CharField(choices=[('hero', 'Encabezado Principal'), ('stats', 'Barra de Estadísticas'), ('steps', 'Pasos / Proceso'), ('features', 'Características / Cards'), ('cta', 'Call to Action / Banner'), ('evento', 'Evento Destacado'), ('pasado', 'Evento Pasado / Noticia'), ('custom', 'Bloque Personalizado')], default='hero', max_length=20),
        ),
    ]
