# Generated by Django 5.2.11 on 2026-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_landingbloque_items_json_alter_landingbloque_estilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='es_lider',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Líder Académico'),
        ),
        migrations.AddField(
            model_name='sesionasistencia',
            name='solo_lideres',
            field=models.BooleanField(default=False, help_text='Solo participantes marcados como líderes pueden registrarse', verbose_name='Solo Líderes Académicos'),
        ),
    ]
