# Generated by Django 5.2.11 on 2026-03-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_participante_es_lider_sesionasistencia_solo_lideres'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Autoridad')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('imagen', models.TextField(verbose_name='Firma (Base64)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma Institucional',
                'verbose_name_plural': 'Firmas Institucionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='firma_inst_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_firma1', to='core.firmainstitucional', verbose_name='Firma Institucional 1'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='firma_inst_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_firma2', to='core.firmainstitucional', verbose_name='Firma Institucional 2'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='firma_inst_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_firma3', to='core.firmainstitucional', verbose_name='Firma Institucional 3'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='firma_inst_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_firma4', to='core.firmainstitucional', verbose_name='Firma Institucional 4'),
        ),
    ]
