# Generated by Django 5.2.11 on 2026-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_firmainstitucional_lotecertificados_firma_inst_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmainstitucional',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Firma Institucional', 'verbose_name_plural': 'Firmas Institucionales'},
        ),
        migrations.AddField(
            model_name='firmainstitucional',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden por defecto'),
        ),
        migrations.AlterField(
            model_name='firmainstitucional',
            name='imagen',
            field=models.TextField(blank=True, default='', verbose_name='Firma (Base64)'),
        ),
        migrations.AlterField(
            model_name='firmainstitucional',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Autoridad'),
        ),
    ]
