# Generated by Django 5.2.11 on 2026-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_firmas_institucionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecertificados',
            name='cargo_firma_1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo Autoridad 1'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='cargo_firma_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo Autoridad 2'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='nombre_firma_1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Autoridad 1'),
        ),
        migrations.AlterField(
            model_name='lotecertificados',
            name='nombre_firma_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Autoridad 2'),
        ),
    ]
