# Generated by Django 5.2.11 on 2026-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_firma_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecertificados',
            name='cuerpo_certificado',
            field=models.TextField(default="Por haber completado satisfactoriamente el curso de capacitación continua, demostrando compromiso y excelencia académica. Por su participación en el seminario '{curso}', contribuyendo de manera activa y profesional al desarrollo de nuevas competencias.", help_text='Texto principal del certificado'),
        ),
    ]
