# Generated by Django 5.2.11 on 2026-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_personalizar_diseno_and_reset_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenoglobal',
            name='posicion_firmas',
            field=models.FloatField(default=4.2, help_text='Distancia desde el borde inferior en centímetros. Mayor = más arriba.', verbose_name='Posición vertical de firmas (cm)'),
        ),
        migrations.AddField(
            model_name='lotecertificados',
            name='posicion_firmas',
            field=models.FloatField(default=4.2, help_text='Distancia desde el borde inferior. Mayor = más arriba.', verbose_name='Posición vertical de firmas (cm)'),
        ),
    ]
