# Generated by Django 5.2.11 on 2026-04-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_posicion_firmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_1_escala',
            field=models.FloatField(default=100, help_text='Escala firma 1 (%)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_1_offset_y',
            field=models.FloatField(default=0, help_text='Ajuste vertical firma 1 (cm)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_2_escala',
            field=models.FloatField(default=100, help_text='Escala firma 2 (%)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_2_offset_y',
            field=models.FloatField(default=0, help_text='Ajuste vertical firma 2 (cm)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_3_escala',
            field=models.FloatField(default=100, help_text='Escala firma 3 (%)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_3_offset_y',
            field=models.FloatField(default=0, help_text='Ajuste vertical firma 3 (cm)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_4_escala',
            field=models.FloatField(default=100, help_text='Escala firma 4 (%)'),
        ),
        migrations.AddField(
            model_name='disenoglobal',
            name='firma_4_offset_y',
            field=models.FloatField(default=0, help_text='Ajuste vertical firma 4 (cm)'),
        ),
    ]
