# Generated by Django 5.2.11 on 2026-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_duplicate_participantes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_email_when_not_empty'),
        ),
    ]
