# Generated by Django 5.2.13 on 2026-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_sesion_modalidad_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(blank=True, choices=[('FACI', 'FACI - Ingeniería'), ('FACS', 'FACS - Salud'), ('FACE', 'FACE - Educación'), ('FACSECYD', 'FACSECYD - Ciencias Sociales'), ('POSGRADO', 'Posgrado / Otra')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador')], db_index=True, default='admin', max_length=20),
        ),
    ]
