# Generated by Django 5.2.11 on 2026-04-20 00:27

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_indexes_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='lotecertificados',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Lote de Certificados', 'verbose_name_plural': 'Lotes de Certificados'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['-created_at'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterUniqueTogether(
            name='confirmacionasistencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='hash_verificacion',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[core.validators.validar_cedula_ecuador]),
        ),
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20, validators=[core.validators.validar_telefono_ecuador]),
        ),
        migrations.AlterField(
            model_name='solicitudacceso',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validar_telefono_ecuador], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validar_telefono_ecuador]),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['lote', '-created_at'], name='core_certif_lote_id_fc11c2_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['cedula', 'email'], name='core_certif_cedula_325478_idx'),
        ),
        migrations.AddIndex(
            model_name='lotecertificados',
            index=models.Index(fields=['activo', '-fecha_creacion'], name='core_lotece_activo_b0b46f_idx'),
        ),
        migrations.AddIndex(
            model_name='lotecertificados',
            index=models.Index(fields=['facultad'], name='core_lotece_faculta_64ea4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(condition=models.Q(('horas__gte', 0)), name='certificado_horas_no_negativas'),
        ),
        migrations.AddConstraint(
            model_name='confirmacionasistencia',
            constraint=models.UniqueConstraint(fields=('participante', 'sesion'), name='unique_confirmacion_participante_sesion'),
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('sesion', 'participante'), name='unique_registro_sesion_participante'),
        ),
    ]
