# Generated by Django 5.2.13 on 2026-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_certificado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Cuenta Google conectada', max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(help_text='Token de larga duración para auto-refrescar')),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(help_text='TODO Fase 11: cifrar con django-cryptography', max_length=200)),
                ('scopes', models.JSONField(default=list)),
                ('expiry', models.DateTimeField(blank=True, help_text='Cuándo expira el access_token', null=True)),
            ],
            options={
                'verbose_name': 'Credencial Google',
                'verbose_name_plural': 'Credenciales Google',
            },
        ),
    ]
