# Generated by Django 5.2.13 on 2026-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_googlecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionasistencia',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID del evento en Google Calendar (para actualizarlo o eliminarlo).', max_length=200),
        ),
        migrations.AddField(
            model_name='sesionasistencia',
            name='transcripcion_habilitada',
            field=models.BooleanField(default=True, help_text='Si está activo, el transcript de Meet se procesa con IA tras la sesión.', verbose_name='Generar resumen IA del evento'),
        ),
    ]
