# Generated by Django 5.2.13 on 2026-04-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sesionasistencia_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('titulo', models.CharField(blank=True, default='', help_text='Ej.: Dr., Mgs., Ing., PhD', max_length=100, verbose_name='Título / Cargo')),
                ('afiliacion', models.CharField(blank=True, default='', help_text='Ej.: UNEMI, MIT, Stanford', max_length=200, verbose_name='Afiliación / Institución')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografía corta')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponentes', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Ponente',
                'verbose_name_plural': 'Ponentes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
