# Generated by Django 5.2.13 on 2026-04-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_ponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI (GPT)'), ('groq', 'Groq (Llama / Mixtral)')], default='claude', max_length=20, verbose_name='Proveedor de IA')),
                ('model', models.CharField(blank=True, default='claude-haiku-4-5', help_text='Identificador del modelo según el proveedor (ej. claude-haiku-4-5).', max_length=80, verbose_name='Modelo')),
                ('api_key', models.CharField(blank=True, default='', help_text='TODO Fase 11: cifrar con django-cryptography.', max_length=500)),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 = más determinista, 1.0 = más creativo.')),
                ('max_tokens', models.PositiveIntegerField(default=1024, help_text='Tope máximo de tokens en la respuesta.')),
                ('system_prompt_override', models.TextField(blank=True, default='', help_text='Si se llena, se antepone a todos los prompts del sistema.', verbose_name='System prompt global (opcional)')),
                ('enabled', models.BooleanField(default=False, help_text='Si está apagado, todas las features de IA quedan deshabilitadas.')),
            ],
            options={
                'verbose_name': 'Configuración IA',
                'verbose_name_plural': 'Configuración IA',
            },
        ),
    ]
