# Generated by Django 5.2.13 on 2026-04-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_aiconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingBloque',
        ),
    ]
