# Generated by Django 5.2.13 on 2026-04-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_delete_landingbloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDesignTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_brand', models.CharField(default='#F58830', help_text='Color de marca principal (acento UNEMI / CertifAI)', max_length=9)),
                ('color_brand_dark', models.CharField(default='#D97520', help_text='Variante oscura del color de marca (gradientes/hover)', max_length=9)),
                ('color_accent', models.CharField(default='#A855F7', help_text='Acento secundario (badges decorativos)', max_length=9)),
                ('color_bg_dark', models.CharField(default='#0A1535', help_text='Fondo principal modo oscuro', max_length=9)),
                ('color_bg_light', models.CharField(default='#F8FAFC', help_text='Fondo principal modo claro', max_length=9)),
                ('color_card_dark', models.CharField(default='#152448', help_text='Fondo de cards modo oscuro', max_length=9)),
                ('color_card_light', models.CharField(default='#FFFFFF', help_text='Fondo de cards modo claro', max_length=9)),
                ('color_text_dark', models.CharField(default='#E2E8F0', help_text='Texto principal modo oscuro', max_length=9)),
                ('color_text_light', models.CharField(default='#0F172A', help_text='Texto principal modo claro', max_length=9)),
                ('color_text_muted_dark', models.CharField(default='#94A3B8', help_text='Texto secundario modo oscuro', max_length=9)),
                ('color_text_muted_light', models.CharField(default='#64748B', help_text='Texto secundario modo claro', max_length=9)),
                ('color_success', models.CharField(default='#10B981', max_length=9)),
                ('color_danger', models.CharField(default='#EF4444', max_length=9)),
                ('color_warning', models.CharField(default='#F59E0B', max_length=9)),
                ('color_info', models.CharField(default='#3B82F6', max_length=9)),
                ('font_sans', models.CharField(default="'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif", help_text='Stack de fuente para UI general', max_length=255)),
                ('font_display', models.CharField(default="'Sora', 'Inter', system-ui, sans-serif", help_text='Stack de fuente para títulos/branding', max_length=255)),
                ('font_mono', models.CharField(default="'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, monospace", help_text='Stack de fuente monoespaciada (códigos, IDs)', max_length=255)),
                ('radius_sm', models.CharField(default='0.5rem', help_text='Radio chico (8px)', max_length=10)),
                ('radius_md', models.CharField(default='0.75rem', help_text='Radio medio (12px)', max_length=10)),
                ('radius_lg', models.CharField(default='1rem', help_text='Radio grande (16px)', max_length=10)),
                ('radius_xl', models.CharField(default='1.5rem', help_text='Radio xl (24px) — cards', max_length=10)),
                ('btn_blur', models.CharField(default='40px', help_text='Backdrop-filter blur en botones lg-btn', max_length=10)),
                ('btn_saturate', models.CharField(default='180%', help_text='Backdrop-filter saturate', max_length=10)),
                ('btn_glass_opacity_dark', models.FloatField(default=0.18, help_text='Opacidad del fondo del botón en oscuro (0-1)')),
                ('btn_glass_opacity_light', models.FloatField(default=0.92, help_text='Opacidad del fondo del botón en claro (0-1)')),
                ('shadow_card', models.CharField(default='0 8px 32px -4px rgba(0,0,0,0.35), 0 2px 8px -2px rgba(0,0,0,0.20)', help_text='Sombra de cards (lg-card) — modo oscuro', max_length=255)),
                ('shadow_card_light', models.CharField(default='0 4px 16px -4px rgba(15,23,42,0.08), 0 1px 4px -1px rgba(15,23,42,0.04)', help_text='Sombra de cards en modo claro', max_length=255)),
            ],
            options={
                'verbose_name': 'Design System',
                'verbose_name_plural': 'Design System',
            },
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model',
            field=models.CharField(blank=True, default='claude-haiku-4-5-20251001', help_text='Identificador del modelo según el proveedor (ej. claude-haiku-4-5-20251001).', max_length=80, verbose_name='Modelo'),
        ),
    ]
