# Generated by Django 5.2.13 on 2026-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_uidesigntokens_alter_aiconfig_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil (opcional).', null=True, upload_to='participantes/avatars/'),
        ),
        migrations.AddField(
            model_name='participante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='password_hash',
            field=models.CharField(blank=True, default='', help_text='Hash PBKDF2 (Django). Vacío = guest (sin cuenta).', max_length=255),
        ),
    ]
