# Generated by Django 5.2.13 on 2026-04-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_participante_avatar_participante_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uidesigntokens',
            name='color_accent',
            field=models.CharField(default='#162054', help_text='Acento secundario · UNEMI azul institucional', max_length=9),
        ),
        migrations.AlterField(
            model_name='uidesigntokens',
            name='color_danger',
            field=models.CharField(default='#DC2626', help_text='Errores críticos · rojo', max_length=9),
        ),
        migrations.AlterField(
            model_name='uidesigntokens',
            name='color_info',
            field=models.CharField(default='#3B82F6', help_text='Información · azul claro', max_length=9),
        ),
        migrations.AlterField(
            model_name='uidesigntokens',
            name='color_success',
            field=models.CharField(default='#1E40AF', help_text='Estado positivo · azul', max_length=9),
        ),
        migrations.AlterField(
            model_name='uidesigntokens',
            name='color_warning',
            field=models.CharField(default='#F58830', help_text='Aviso · naranja brand', max_length=9),
        ),
        migrations.CreateModel(
            name='ParticipanteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.participante')),
            ],
            options={
                'verbose_name': 'Token de participante',
                'verbose_name_plural': 'Tokens de participantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='core_partic_expires_dc1b4e_idx')],
            },
        ),
    ]
