# Generated by Django 5.2.13 on 2026-05-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_uidesigntokens_color_accent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(blank=True, db_index=True, default='', help_text='ID del documento de transcript en Google Drive.', max_length=200)),
                ('drive_file_name', models.CharField(blank=True, default='', help_text='Nombre del archivo de transcript en Drive (referencia).', max_length=300)),
                ('transcript_raw', models.TextField(blank=True, default='', help_text='Texto plano del transcript (parseado, sin formato).')),
                ('transcript_chars', models.IntegerField(default=0, help_text='Cantidad de caracteres del transcript (para auditoría).')),
                ('resumen_md', models.TextField(blank=True, default='', help_text='Resumen ejecutivo en Markdown (puntos clave + decisiones).')),
                ('puntos_clave', models.JSONField(blank=True, default=list, help_text='Lista de strings: bullet points del evento.')),
                ('proximos_pasos', models.JSONField(blank=True, default=list, help_text='Lista de strings: acciones recomendadas post-evento.')),
                ('cuestionario', models.JSONField(blank=True, default=list, help_text='Lista de preguntas para repasar lo aprendido. Formato: [{pregunta, opciones: [...], correcta_idx, explicacion}]')),
                ('duracion_minutos', models.IntegerField(default=0, help_text='Duración estimada del evento (de transcript timestamps).')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('buscando', 'Buscando transcript'), ('procesando', 'Procesando con IA'), ('listo', 'Listo'), ('sin_transcript', 'Sin transcript'), ('fallido', 'Fallido')], db_index=True, default='pendiente', max_length=20)),
                ('error_msg', models.TextField(blank=True, default='', help_text='Stack trace si estado=fallido.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.CharField(blank=True, default='', max_length=80)),
                ('ai_input_tokens', models.IntegerField(default=0)),
                ('ai_output_tokens', models.IntegerField(default=0)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Resumen IA de sesión',
                'verbose_name_plural': 'Resúmenes IA de sesiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
