# Generated by Django 5.2.13 on 2026-05-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_resumensesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctas', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('tiempo_total_seg', models.PositiveIntegerField(default=0)),
                ('respuestas', models.JSONField(blank=True, default=list, help_text='Lista de índices elegidos por el participante (null = sin responder).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionario', to='core.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionario', to='core.sesionasistencia')),
            ],
            options={
                'verbose_name': 'Intento de cuestionario',
                'verbose_name_plural': 'Intentos de cuestionario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participante', 'sesion'], name='core_intent_partici_b42b01_idx')],
            },
        ),
    ]
