# Generated by Django 5.2.13 on 2026-05-13 18:00

import core.base.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0051_intentocuestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código corto único (ej. FACI, FACS). Usado en FK desde otros modelos.', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la facultad (ej. "FACI - Ingeniería").', max_length=120)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción opcional de la facultad.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en selects. Menor = primero.')),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Si está desactivada, no aparece en selects pero conserva las relaciones existentes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='sesionasistencia',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='cambios',
            field=models.JSONField(blank=True, default=dict, help_text='Diff campo→{antes, despues}. Vacío si no aplica (ej. LOGIN).'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de modelo del objeto auditado (ej. Certificado, Sesión).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='PK del objeto auditado.', null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='api_key',
            field=core.base.fields.EncryptedCharField(blank=True, default='', help_text='Cifrado at-rest con Fernet. Solo visible para Python (no SQL).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('DESCARGAR', 'Descargar archivo'), ('OTRA', 'Otra acción')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='detalle',
            field=models.TextField(blank=True, default='', help_text='Descripción humana de la acción (compat con logs legacy).'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='access_token',
            field=core.base.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='client_secret',
            field=core.base.fields.EncryptedCharField(help_text='Cifrado at-rest con Fernet', max_length=500),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='refresh_token',
            field=core.base.fields.EncryptedTextField(help_text='Token de larga duración para auto-refrescar'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['content_type', 'object_id'], name='core_audito_content_14915a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion', '-fecha'], name='core_audito_accion_1a0ed4_idx'),
        ),
    ]
